### PR TITLE
Use sigs.k8s.io/yaml everywhere

### PR DESCRIPTION
**Pull request by hezhizhen**

### CODE REVIEW

**Review by hiddeco — COMMENTED** [review]
Good catch, and likely the result of some past merge-conflict. Looking at the Helm source however, `sigs.k8s.io/yaml` is used. Given this, I think the change should be made in `values.go` and not in the test.

**Comment by hezhizhen** [comment]
> Good catch, and likely the result of some past merge-conflict. Looking at the Helm source however, `sigs.k8s.io/yaml` is used. Given this, I think the change should be made in `values.go` and not in the test.

So I should replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml` not vice versa?

**Comment by hiddeco** [comment]
Correct.

**Comment by hezhizhen** [comment]
Done.

**Review by hiddeco — APPROVED** [review]
Thank you @hezhizhen :tulip:

**Pull request merged**
