### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by kingdonb**
The changelog has been added in #620 - this is the last update prior to CRD v1 and the next version requires Kubernetes 1.16+ or greater.

The updates were tested in parallel with #621 (for Release 1.4.0), these builds passed all release validation checks.

### CODE REVIEW

**Comment by kingdonb** [comment]
I kicked off a new build, we apparently have a flaky test around this point in the e2e:

```
>>> Waiting for no helm-operator restarts  done
ok 7 When rollback.enable is set, releases with failed waits are rolled back
service/gitsrv created
deployment.apps/gitsrv created
>>> Waiting for tiller ready  done
helmrelease.helm.fluxcd.io/podinfo-helm-repository created
>>> Waiting for release deploy .... done
helmrelease.helm.fluxcd.io/podinfo-helm-repository patched
>>> Waiting for upgrade failure .......... done
>>> Waiting for rollback count == 3 ........................ No more retries left!
not ok 8 When rollback.retry is set, upgrades are reattempted after a rollback
# (from function `poll_until_true' in file ./lib/poll.bash, line 26,
#  from function `poll_until_equals' in file ./lib/poll.bash, line 9,
#  in test file ./20_rollbacks.bats, line 56)
#   `poll_until_equals 'rollback count == 3' '3' "kubectl -n $DEMO_NAMESPACE get helmrelease/podinfo-helm-repository -o jsonpath='{.status.rollbackCount}'"' failed
# namespace/helm-operator-e2e created
# Generating public/private rsa key pair.
```

**Comment by kingdonb** [comment]
@hiddeco Do you want to wait until after Flux v2 0.16.0 is out before I cut these releases

**Comment by kingdonb** [comment]
I saw that there were merge conflicts generated when I merged #618 and #599, I've resolved them so they can be included in the review. Assuming this passes the build and gets approved, I plan to release 1.3.0 tomorrow and 1.4.0 on the next day.

The changelog entries are updated in the latest commit on each release branch, to reflect the new correct release dates.

I may end up needing to open one more housekeeping PR back to master afterwards based on the branch protection rules, (I was hoping to avoid it by planning the merges strategically, and may still be able to do so.) But after going through all of that just now, I'm thinking it will be easier to simply wait until after the release, and open it then or whenever needed.

**Review by hiddeco — APPROVED** [review]

**Comment by kingdonb** [comment]
This release branch will not get merged into master, since it contains conflicts that will revert the 1.4.0 work if merged.

The way forward for supported users is Helm Controller, but failing that, we're providing 1.4.0 to ensure forward compatibility for users who cannot upgrade from Helm Operator for whatever reason, and 1.3.0 for users who cannot upgrade Kubernetes and cannot upgrade to Helm Controller for whatever reason.

Future releases of the 1.3.0 branch are unlikely, but it is still technically possible.

The `release/1.3.x` branch will go unmaintained after 1.3.0 is published, and users will be required to upgrade in order to receive any further patches. This is presuming that everything goes fine and there are not any surprising show-stoppers in there that somehow evaded detection by e2e tests, (in that case we can add a new release to the `release/1.3.x` branch.)

I will publish both releases 1.3.0 and 1.4.0 inside of the next 2 days.

**Pull request merged**
