### PR TITLE
Update Helm stable repository url

### PR DESCRIPTION
**Pull request by em-schmidt**

### CODE REVIEW

**Comment by chrisjholly** [comment]
Hi @em-schmidt  - There is a workaround in the CNCF slack: https://cloud-native.slack.com/archives/CLAJ40HV3/p1609242081045300?thread_ts=1608719917.436400&cid=CLAJ40HV3

**Review by blaquezzz — APPROVED** [review]

**Comment by yebyen** [comment]
@kingdonb

**Review by hiddeco — APPROVED** [review]
Thank you @em-schmidt :100:

**Comment by hiddeco** [comment]
Victory!

**Pull request merged**
