### PR TITLE
pkg: Helm 2.16.4

### PR DESCRIPTION
**Pull request by hiddeco**
- [x] Go library `2.16.3` -> `2.16.4`
- [x] Binaries `2.16.3` -> `2.16.4`

### CODE REVIEW

**Comment by stefanprodan** [comment]
Helm 2.16.4 is broken as far as I can tell, same error as in https://github.com/fluxcd/flux/issues/2935

**Comment by hiddeco** [comment]
Looks like that indeed, lets wait for `2.16.5`.

**Comment by stefanprodan** [comment]
It's so hard to tell where is the actual error in the e2e tests... can we exit right after an error?

**Comment by hiddeco** [comment]
I often use the information printed after the error to debug things. The errors are repeated `validation failed: ...` errors.

**Pull request closed without merging**
