### PR TITLE
Updated deploy/rbac.yaml ClusterRole and ClusterRoleBinding to V1

### PR DESCRIPTION
**Pull request by jfilipcz**
Bumping deploy/rbac.yaml ClusterRole and ClusterRoleBinding to V1. It's already updated on v1.4.1 in the chart itself.

### CODE REVIEW

**Comment by kingdonb** [comment]
Thanks! I have been switching back and forth between 1.21 and 1.22, so this slipped by my testing!

Now that 1.23 is out, we should definitely wrap up these issues and support 1.22+ – have you tested with these changes and find everything is OK on the new releases? (Are there any other open issues that you'd really like to see attended to?)

**Review by kingdonb — APPROVED** [review]
LGTM

**Comment by jfilipcz** [comment]
> Thanks! I have been switching back and forth between 1.21 and 1.22, so this slipped by my testing!
> 
> Now that 1.23 is out, we should definitely wrap up these issues and support 1.22+ – have you tested with these changes and find everything is OK on the new releases? (Are there any other open issues that you'd really like to see attended to?)

Testing atmo, if I find anything else I will report back:)

**Comment by kingdonb** [comment]
Cool – I just noticed that you said we did manage to include these changes in the chart already, and this one is just for those who are deploying from the manifests directory. If I got it right that means we can just merge this, and no follow-up release is needed. 👍 

Thanks for your contribution here!

**Comment by oybed** [comment]
@kingdonb I do believe we'll need a new release of this repo - if possible. Right now, some of our processes sources these files from the specific release/tag, and currently `v1.4.1` is "broken" for our use because of this. Any chance we can get a `v1.4.2` release soon-ish?

**Comment by kingdonb** [comment]
Sure, @oybed see #643 – I'll follow this up soon. 👍

**Comment by bmaehr** [comment]
I'm still getting this error: 
```
module.kubernetes_resources.null_resource.helm_operator (local-exec): Executing: ["/bin/sh" "-c" "helm upgrade -i helm-operator helm-operator --repo https://charts.fluxcd.io/ --version 1.4.2 -n management --set initPlugins.enable=true --set 'initPlugins.plugins[0].plugin=https://github.com/hayorov/helm-gcs.git' --set 'initPlugins.plugins[0].version=0.3.21' --set 'initPlugins.plugins[0].helmVersion=v3' --set 'helm.versions=v3'"]
module.kubernetes_resources.null_resource.helm_operator (local-exec): Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"]
```
Any idea?

EDIT:
```
helm uninstall helm-operator -n management
```
did solve it

**Pull request merged**
