### PR TITLE
Helm v3 support

### PR DESCRIPTION
**Pull request by hiddeco**
This PR merges `helm-v3-dev` into `master`, and thereby promotes the support for Helm v3 from alpha to beta.

All work done and available in the `helm-v3-dev` range will be available in the next release candidate (`RC5`).

### CODE REVIEW

**Review by 2opremio — APPROVED** [review]

**Comment by 2opremio** [comment]
🏅 🎖 🥇 Awesome job getting this out!

**Comment by stefanprodan** [comment]
I see "Validation error does not trigger rollback" is the test flaky?

**Comment by hiddeco** [comment]
@stefanprodan it suddenly started failing after the merge to `helm-v3-dev`, it succeeds however locally (ran it multiple times) so I am clueless at this point.

**Review by stefanprodan — APPROVED** [review]
LGTM 🎖

**Pull request merged**
