### PR TITLE
Enable additional sidecar containers

### PR DESCRIPTION
**Pull request by nilesh892003**

### CODE REVIEW

**Review by hiddeco — COMMENTED** [review]
Thank you for your PR :tulip: 

Can you please document the added field?

**Comment by nilesh892003** [comment]
> Thank you for your PR 🌷
> 
> Can you please document the added field?

Thank you, i have added the document line in chart references for this new field.

**Review by stefanprodan — APPROVED** [review]
LGTM

Please rebase with master and squash all commits into one.

**Comment by nilesh892003** [comment]
> LGTM
> 
> Please rebase with master and squash all commits into one.

Rebased PR and squashed all the commits. thank you

**Pull request merged**
