### PR TITLE
fix: add manifest diff when diff releases

### PR DESCRIPTION
**Pull request by Kaggggggga**
This PR is to additionally detect changes on the helm generated manifest.
I am not sure it is intended or not, originally it only detects change on the Chart and the values.
The old mechanism did not work well when I updated the chart dependencies version without updating the chart itself. 

PS. The manifest changes should already cover the chart and value changes, but I think I should make the minimum changes to draft my changes first, feel free to let me know which is preferred

Feel free to let me know what else I have missed or the reason behind the original design

### CODE REVIEW

**Review by hiddeco — COMMENTED** [review]
Thanks for your contribution but this has been left out on purpose due to the fact that the manifest can contain generated values that differ on every dry-run. The comparison of the chart metadata should already catch changes made to the chart as this includes the template files and values of the chart.

I am however aware that this solution may not be watertight at the moment given #337, but including manifests will not reliably resolve this.

**Comment by Kaggggggga** [comment]
Understood, thanks for the reply

I thought about the generated-variable case of us too, but we put it out of automation workflow at last, or try to make it depend on deployment variables, such as image tag

technically speaking, it seems the Chart object should include updated dependences files contents too

**Comment by hiddeco** [comment]
> The old mechanism did not work well when I updated the chart dependencies version without updating the chart itself.

Can you elaborate on this a bit? I created a Git sourced [dummy chart](https://github.com/hiddeco/test-charts/tree/dependencies) and let the Helm Operator install it. I then changed the `requirements.yaml` file in Git without making any additional changes to the chart, this resulted in an upgrade.

```log
ts=2020-03-26T11:59:40.747395544Z caller=helm.go:69 component=helm version=v3 info="dry run for
mespace=default release=default-dependencies
ts=2020-03-26T11:59:40.762053235Z caller=release.go:413 component=release release=default-dependencies
 resource=default:helmrelease/dependencies helmVersion=v3 info="no changes" action=skip
ts=2020-03-26T12:01:41.003667684Z caller=logwriter.go:28 component=helm version=v3 info="Saving 1 charts"
ts=2020-03-26T12:01:41.003914864Z caller=logwriter.go:28 component=helm version=v3 info="Downloading redis from repo https://kubernetes-charts.storage.googleapis.com"
ts=2020-03-26T12:01:43.4619495Z caller=logwriter.go:28 component=helm version=v3 info="Deleting outdated charts"
ts=2020-03-26T12:01:43.487604736Z caller=release.go:367 component=release release=default-dependencies targetNamespace=default resource=default:helmrelease/dependencies helmVersion=v3 info="performing dry-run upgrade to see if release has diverged"
ts=2020-03-26T12:01:43.495011665Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for default-dependencies" targetNamespace=default release=default-dependencies
ts=2020-03-26T12:01:43.820931564Z caller=helm.go:69 component=helm version=v3 info="performing
update for default-dependencies" targetNamespace=default release=default-dependencies
ts=2020-03-26T12:01:43.851487389Z caller=helm.go:69 component=helm version=v3 info="dry run for default-dependencies" targetNamespace=default release=default-dependencies
ts=2020-03-26T12:01:43.859331437Z caller=release.go:409 component=release release=default-dependencies targetNamespace=default resource=default:helmrelease/dependencies helmVersion=v3 info="dry-run differed" action=upgrade
ts=2020-03-26T12:01:43.871084493Z caller=helm.go:69 component=helm version=v3 info="preparing upgrade for default-dependencies" targetNamespace=default release=default-dependencies
```

**Comment by Kaggggggga** [comment]
> Can you elaborate on this a bit? I created a Git sourced [dummy chart](https://github.com/hiddeco/test-charts/tree/dependencies) and let the Helm Operator install it. I then changed the `requirements.yaml` file in Git without making any additional changes to the chart, this resulted in an upgrade.

thanks for your reply!

I tested it with `1.0.0-rc9`, with helm2
the project chart stored with git, and the dep chart stored with helm chartmuseum(https://github.com/helm/chartmuseum) with basic auth
i have only requirements.yaml and enabled dep chart update

what i did is that, 
for the dep chart, i added some change to an annotation in template and bump a version from 0.19.0 to 0.20.0, 
for the project chart, i updated the requirements.yaml to `=0.20.0` and submited to git

at last, with manifest diff, it will find my changes and trigger upgrade, otherwise, it shows no changes

----
as a newbie to golang, i added some log to debug to print the release.Chart structure for the `compareRelease`, and it seems the dep-chart pointed to an empty map and then result to no changes?
(or maybe my way of printing object is wrong

```
&{Name:project-chart-name Version:0.1.0 AppVersion: Values:map[dep-chart-name:map[global:map[]]] Templates:[0xc005a45860]}
```

----

feel free to let me know if my information is not enough, i could help on testing on the more generic case if necessary

**Comment by hiddeco** [comment]
Will try to reproduce this again using the steps you gave (likely next Monday). Thanks!

Tests are run on `master-*` builds instead of `1.0.0-rc9` to take fixes since the latest release into account by the way. If you are impatient, it may be worth trying one of the latest [`prerelease` builds](https://hub.docker.com/r/fluxcd/helm-operator-prerelease/tags?ordering=last_updated&page=1) to see if this magically resolves the issue.

**Comment by Kaggggggga** [comment]
> Will try to reproduce this again using the steps you gave (likely next Monday). Thanks!
> 
> Tests are run on `master-*` builds instead of `1.0.0-rc9` to take fixes since the latest release into account by the way. If you are impatient, it may be worth trying one of the latest [`prerelease` builds](https://hub.docker.com/r/fluxcd/helm-operator-prerelease/tags?ordering=last_updated&page=1) to see if this magically resolves the issue.

thanks for the quick response!!
i pull the master and added some log to print the variable, still `no change`
maybe the question is too newbie, i wonder what the best way to print the structure is? 
seems this is not showing the full structure..

```
	fmt.Printf("%+v\n", curRel.Chart)
	fmt.Printf("%+v\n", desRel.Chart)
```

**Comment by hiddeco** [comment]
Try 

```go
	fmt.Printf("%#v\n", curRel.Chart)
	fmt.Printf("%#v\n", desRel.Chart)
```

if that does not work or give you a sufficient amount of information, just get dirty and select all fields that are actually interesting (`Chart.Templates`, `Chart.Values`).

**Comment by Kaggggggga** [comment]
i created an empty chart as the `project chart` with 3 files including 1 file with only comment in templates folder,  the 1 file of the `requirements.yaml` referring to the redis dependency chart that I hosted in my chart museum with semver using `=`,  and also the Chart.yaml

then i created the `` helmrelease referring to this `project chart`, saw resources were created
then i updated annotation in the redis dependency chart, and bumped the version
then i updated the semver `=` in `requirements.yaml` of `project chart`, and push to git
and still see no changes at last, using helm2 btw

----
the helm-operator was built with master branch, and i also added log to print the `Chart.Templates` (ignored `Chart.Values` as it is not updated

```
[]*helm.File{(*helm.File)(0xc015f45230)}
[]*helm.File{(*helm.File)(0xc00ad3a750)}
```

I did not go further as I need sometime to pick up the pointer usage in golang, so I left my test result here first

Thank you for your help!

**Comment by kingdonb** [comment]
Closing, stale.

Thanks for contributing here! Flux v1 and Helm Operator are in maintenance mode 🎉

**Pull request closed without merging**
