### PR TITLE
Add manifest-generating API for installation

### PR DESCRIPTION
**Pull request by 2opremio**
Similarly to https://github.com/fluxcd/flux/pull/2287 , this PR allows other Go programs to generate the Kubernetes manifests necessary to install the helm operator.

I plan to incorporate this into `fluxctl install --with-helm-op`

### CODE REVIEW

**Comment by hiddeco** [comment]
Is the `.tmpl.tmpl` for the template files on purpose?

**Comment by 2opremio** [comment]
No, it was unintentional. You are quick, it took me a couple of minutes to remove them :)

**Comment by 2opremio** [comment]
I am going to need to tweak this further [in order to support TLS](https://docs.fluxcd.io/en/latest/helm-operator/tutorials/get-started.html?highlight=tls#installing-helm-tiller). I can do it in another PR. @hiddeco thoughts?

**Comment by hiddeco** [comment]
@2opremio I won't be able to review this until tomorrow. Can you work in a separate PR without this being merged?

**Comment by 2opremio** [comment]
I won't continue working on this until tomorrow anyways

**Comment by hiddeco** [comment]
Code looks alright to me (it is more or less the same as the existing code in the Flux codebase).

One thing I noticed though is that you did not add the `vfsutil` package to `pkg/tools.go`, is this on purpose or did you forget to add it?

**Comment by 2opremio** [comment]
I forgot. Adding it right away.

**Review by hiddeco — APPROVED** [review]

**Pull request merged**
